site: secretnodes
url: blog.secretnodes.org
author: 
author:
  name: 
  email: 
  url: 
  avatar: 
title: Secret Nodes Blog
description: Secret Nodes - Securing the decentralized web! 
logo: 
image: 
twitter: secretnodes  
twitter:
  username: 
  creator: 
  card: summary
social:
  name: 
  links:
permalink: 

disqus:
  name: "your disqus username" # required
  noscript: "Please enable JavaScript to view the comments powered by Disqus." # optional

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
